When a connection is specified in place of a flow error out nicely
When a connection is specified via -f instead of a flow we get:
Traceback (most recent call last):
  File "./captcp.py", line 5210, in <module>
    sys.exit(captcp.run())
  File "./captcp.py", line 5171, in run
    classinstance.initialize()
  File "./captcp.py", line 4197, in initialize
    self.parse_local_options()
  File "./captcp.py", line 4264, in parse_local_options
    (self.connection_id, self.local_flow_id) =
self.opts.connections.split('.')
ValueError: need more than 1 value to unpack

Error out nicely instead:
You specified a connection not a flow

Signed-off-by: Michele Baldessari <michele@acksyn.org>