Adjust Geoip class so that it works
Currently the geoip module does not work:
$ captcp geoip -h
Traceback (most recent call last):
  File "/usr/share/captcp/captcp.py", line 5210, in <module>
    sys.exit(captcp.run())
  File "/usr/share/captcp/captcp.py", line 5168, in run
    classinstance = globals()[classtring]()
TypeError: __init__() takes exactly 2 arguments (1 given)

Subclass it from mod and also clean up the logging a bit